export const AI_PROVIDERS = {
  OLLAMA: 'ollama',
  MOCK: 'mock',
  OPENAI: 'openai', // future
};

export const DOCUMENT_STATUSES = {
  UPLOADED: 'uploaded',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  FAILED: 'failed',
  ARCHIVED: 'archived',
};

export const CHAT_ROLES = {
  USER: 'user',
  ASSISTANT: 'assistant',
  SYSTEM: 'system',
};

export const FEATURES = {
  AI_CHAT: 'AI_CHAT',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  ANALYTICS: 'ANALYTICS',
  AUDIT_LOGS: 'AUDIT_LOGS',
  CUSTOM_BRANDING: 'CUSTOM_BRANDING',
  API_ACCESS: 'API_ACCESS',
  PRIORITY_SUPPORT: 'PRIORITY_SUPPORT',
};

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  MANAGER: 'MANAGER',
  KNOWLEDGE_MANAGER: 'KNOWLEDGE_MANAGER',
  AGENT: 'AGENT',
};

export const PERMISSIONS = {
  MANAGE_COMPANY: 'MANAGE_COMPANY',
  MANAGE_USERS: 'MANAGE_USERS',
  UPLOAD_DOCUMENTS: 'UPLOAD_DOCUMENTS',
  VIEW_DOCUMENTS: 'VIEW_DOCUMENTS',
  ASK_QUESTIONS: 'ASK_QUESTIONS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_AI_SETTINGS: 'MANAGE_AI_SETTINGS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_SUBSCRIPTION: 'MANAGE_SUBSCRIPTION',
};

export const FILE_SIZE_LIMITS = {
  DOCUMENT: 50 * 1024 * 1024, // 50MB
};

export const ALLOWED_FILE_TYPES = ['application/pdf', 'text/plain', 'text/markdown'];
